### ISSUE TITLE
Pull documentation is out of date since the introduction of alembic

### ISSUE THREAD

**Issue by stathissideris** [zcaudate/lucidity#23]
The example in the pull documentation is misleading, since alembic requires you to pass a version of the dependency and does not automatically retrieve the latest (at least not with the syntax shown). Also, the confinguration does not mention the alembic dependency despite it not being included in the project.clj of vinyasa.

**Comment by zcaudate** [comment]
Thanks for bringing this up. I didn't think it was an issue but it's great that you've highlighted it. I've been a little distracted recently but will update this on the weekend

**Comment by zcaudate** [comment]
i think this can be closed
