### ISSUE TITLE
Boot support

### ISSUE THREAD

**Issue by arichiardi** [zcaudate/lucidity#27]
Hell @zcaudate!

I am asking at the same time on Slack to the `#boot` channel but I wanted to open an issue here as well. Is there a way to achieve injection in `clojure.core` for boot projects as well?

I guess probably the key `:injections` is missing but it might be easy to add.

Maybe I am just missing a pointer to the right place or documentation (that I can add btw).

Thanks, this is a monster project in my opinion! :smile:

**Comment by zcaudate** [comment]
Hey Andrea,

I’m not too familiar with the boot initialisation process but anywhere you can hook in the calls within :injections should be sufficient. Would be great if you can update me on the solution!

**Comment by arichiardi** [comment]
Actually the solution is pretty simple, and come directly from them :simile:
Anywhere in the `build.boot` script you need to add:

`(intern (the-ns 'clojure.core) something)`

I will try it with vyniasa and let you know :wink:

**Comment by zcaudate** [comment]
i'm closing this as i think it's solved
