### ISSUE TITLE
How to inject an anonymous function?

### ISSUE THREAD

**Issue by raxod502** [zcaudate/lucidity#30]
The following `:injections` will inject a number of functions into the `.` namespace.

```
(require 'vinyasa.inject)
(vinyasa.inject/in
  [clojure.core [refer-clojure rc]]
  [clojure.java.shell sh]
  [clojure.pprint pp pprint]
  [clojure.repl doc pst source]
  [vinyasa.inject [in inject]])
```

This will work fine for any function that is already defined in another namespace, but what if I want to inject my own functions? For instance, suppose I want to be able to use `./out` to refer to the following function:

```
(fn out
  ([obj]
   (out 3 obj))
  ([print-length obj]
   (binding [*print-length* print-length]
     (clojure.pprint/pprint obj))))
```

What would be the best way of doing this—that is, injecting an anonymous or otherwise previously undefined function into the `.` namespace?

**Comment by zcaudate** [comment]
hey!

apologies for the late reply. You can define a function in the :injections
vector in project.clj and inject in that way? I don't know actually. is
that any help?

**Comment by raxod502** [comment]
Hmm… I was hoping to avoid polluting whatever the *initial* namespace happens to be with my function definition.

Also, if I understand correctly, vinyasa can only inject fully namespaced symbols. (At least, this is the extent of my knowledge of how to use it.) So I would have to somehow namespace the symbol `out` with whatever the initial namespace happens to be… and when things start getting this hacky, I start wondering if there isn't a better way to do it.

**Comment by zcaudate** [comment]
hmmm... what do you mean by initial namespace? I would have a utility library that loads my stuff. it's easier to manage and deploy

**Comment by raxod502** [comment]
Well, I mean whatever namespace the REPL starts in. I would have assumed that any `def`s in the `:injections` would end up defining vars in that namespace. I would rather not have an actual separate dependency for just one or two simple utility functions.

But I really need to do some more research about this.

**Comment by zcaudate** [comment]
I think unless specified otherwise, all defs go into the `user`
namespace... i.e. `user/foo`

**Comment by zcaudate** [comment]
i'm closing this
