### ISSUE TITLE
Pull example doesn't work

### ISSUE THREAD

**Issue by winks** [zcaudate/lucidity#34]
Leiningen 2.7.0 on Java 1.8.0_111 OpenJDK 64-Bit Server VM (Debian testing)

Was trying out http://docs.caudate.me/lucidity/lucid-package.html#entry__lucid_package__pull 

  * added `[im.chit/lucid.package "1.2.8"]` to project.clj in 2 different projects
  * Used clojure 1.8
  * got this error:
```

user=> (use 'lucid.package)

CompilerException java.io.FileNotFoundException: Could not locate hara/io/encode__init.class or hara/io/encode.clj on classpath., compiling:(lucid/package/privacy.clj:1:1) 
```

**Comment by zcaudate** [comment]
@winks, can you add `[im.chit/hara.io.encode "2.4.8"]` as a dev dependency for now. I'll add it in in the next release.

**Comment by winks** [comment]
@zcaudate Thanks, that worked.

Still getting an error when pulling something from clojars (`[winks/battlenet "0.4.0"]`) but I'm reasonably sure that's my fault, as other stuff (from maven central) works.
