### ISSUE TITLE
Cross references should be links

### ISSUE THREAD

**Issue by brosenan** [zcaudate/lucidity#35]
When defining a tag to a part of a document (e.g., `[[:section {:tag "foo" :title "Foo"}]]`) it is possible to reference it from anywhere in the document using a double brace: `{{foo}}`.  However, when doing so, the double brace is only replaced with the section number.  I would expect the number to also link to the section.

Further enhancement: based on an option, also allow this to actually spell out "section 1.2", not only "1.2".

**Comment by zcaudate** [comment]
uhhh... I feel like you can just spell 'section' before the 1.2 and it'll be fine. you can create a link by using the [link](#foo) markup thing
