### ISSUE TITLE
Best practices for lucid.distribute

### ISSUE THREAD

**Issue by neverfox** [zcaudate/lucidity#38]
The deprecated `lein-repack` was a lein plugin that gave the developer lein commands for deploying split libraries, but, from what I can tell, `lucid.distribute` only offers basic Clojure functions to accomplish the same thing. Is there a lein plugin to go along with it? If not, what are the best practices for setting up a deployment pipeline to automate distribution, e.g. CI/CD. I couldn't gather anything obvious looking at this or the hara repository, such as a one-off clj file that might contain deployment "scripts".

**Comment by zcaudate** [comment]
@neverfox: lein-repack still works... though thanks for pointing this out. The main advantage of lucid.distribute is that it is completely independent of leiningen, pomegrante, builtitude, gpg... etc and is meant to be used as an in-repl-tool. Like functionality-wise it's lean but it does the job.

I've not really thought about automated deployments but lein-repack works for that. I would advise just building the pipeline with that.

**Comment by neverfox** [comment]
I see. Unfortunately, lein-repack seems to get some of my dependencies wrong, where lucid doesn't. Just curious, since you have lucid.distribute configured for, say, hara, are you essentially deploying new releases from the repl?

**Comment by neverfox** [comment]
I was able to get lein-repack to do the right thing after adding some exclusions that wouldn't normally be necessary in a full jar (because I was already declaring the dependency explicitly). I had declared dependency A (which normally depends on B) and also declared B (which overrides the subdependency in A, of course). Then I had two branches, one of which depends on A and B and one which depends only on B. `lein-repack` have the second branch dependency A instead of just B, I suppose because A includes B *in isolation* and I guess it saw that without taking into account that B was declared itself. `lucid.distribute` didn't make the same mistake. Adding the exclusion to A fixed it, which further suggests to me that `lein-repack` was doing some less sophisticated checking of the dependency tree before making decisions.

**Comment by zcaudate** [comment]
Yeah. I have `hara` configured for deploying from the repl. `lucidity` and `spirit` also. 

I think I added something pretty trivial to `lucid.distribute` but forgot what it was. It's pretty much the same - just the naming has changed. I'm pretty clueless about how the maven dependency resolution works. I'm not sure why it's doing that but I've had particular experiences where having leiningen in the classpath clobbers a whole bunch of dependencies.

**Comment by zcaudate** [comment]
I'm closing this for now.
