### ISSUE TITLE
Query: `^:% predicate` only usable within namespace that defined it

### ISSUE THREAD

**Issue by vemv** [zcaudate/lucidity#41]
Given a custom predicate:

`(defn foo? [a] false)`

And a wrapped query using it:

```
(defn query-it [s]
   (lucid/$ {:string s} [defn :* ^:% foo?]))
```

...said query will be only invokable within that namespace.

From a different ns, I'd have to place this workaround:

```
(def foo? original/foo?)

(original/query-it s)
```

In short, predicate syntax lacks namespace resolution.

Cheers - Victor

**Comment by vemv** [comment]
Hey there,

any chance of having a look at this one? Might be an easy fix, who knows

At work we're using `lucid/$` quite brilliantly for a few purposes, but in some cases the resulting code is not callable at all from other namespaces, greatly reducing its utility and the chances we can reasonably keep relying on this library.

**Comment by zcaudate** [comment]
hey. apologies for the tardy response.

I was thinking of a reply to the first question and then got distracted.

I’m not sure if what you are asking for is possible because the library looks at code and does not evaluate. namespace resolution needs prior knowledge of how clojure works and this is beyond the scope of the library. what you are doing is fine

**Comment by vemv** [comment]
The problem is that while `(def foo? original/foo?)` works, I can only do that in namespaces I control.

If the ClojureScript compiler was to use my macros, I would be unable to apply the same workaround.

Anyway, I found a fix!

For the original example:

```

(ns my.namespace
  ...) ;; a normal ns declaration

(defn foo? [] ...)

(defn query-it [s]
   (lucid/$ {:string s} [defn :* ^:% my.namespace/foo?]))
```

...that is, adding `my.namespace/` to the query.

Thanks for these libraries!
