### ISSUE TITLE
lucid.core.java's reimport doesn't work with zero arguments

### ISSUE THREAD

**Issue by saeidscorp** [zcaudate/lucidity#42]
I remember `(./reimport)` worked fine in `vinyasa`. But in `lucid.core.java` it throws an exception:

```
Usage: javacTask <options> <source files>
where possible options include:
```

Looking at its type signature, it should work like before; compiling all java classes in the project.

What am I missing?!

**Comment by zcaudate** [comment]
can you try stating the classes explicitly? Looking at it, I don't think it ever loaded all classes

**Comment by zcaudate** [comment]
lein vigil does what you want

**Comment by saeidscorp** [comment]
@zcaudate yes, when I specify the classes, it works just fine.

The 0 arity version worked in vinyasa. (I made sure from documentation of this fork of your project: [ardumont/vinyasa](https://github.com/ardumont/vinyasa))

**Comment by zcaudate** [comment]
@saeidscorp. okay it's fixed in https://github.com/zcaudate/lucidity/commit/4c40013fd7c7c6e1e8fb8263228d623e796f591c

`[zcaudate/lucid.core.java "1.4.4"]` has been pushed to clojars.
