### ISSUE TITLE
lucid.aether generated by lein-repack(?) doesn't have any explicit/transient dependencies on hara.object

### ISSUE THREAD

**Issue by saeidscorp** [zcaudate/lucidity#43]
When using `zcaudate/lucid.package` which transiently depends on `lucid.aether`, an exception is thrown saying:
```
java.io.FileNotFoundException: Could not locate hara/object__init.class or hara/object.clj on classpath.
```

If I'm correct, an explicit dependency on `hara.object` is required, and `project.clj` file of `lucid.aether` lacks such entry.

**Comment by zcaudate** [comment]
yes. I can confirm that this is the case.

**Comment by zcaudate** [comment]
can you check ~/.m2/repository/zcaudate/hara.object/2.8.2/hara.object-2.8.2.jar? to see if you can open it

there may have been a problem when uploading to clojars

**Comment by zcaudate** [comment]
I've deployed `[zcaudate/lucidity "1.4.3"]`. 

this should fix the problem.
